// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dummy.sql

package data

import (
	"context"
)

const getSQLiteVersion = `-- name: GetSQLiteVersion :one
SELECT sqlite_version() AS version
`

func (q *Queries) GetSQLiteVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSQLiteVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}
