// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entries.sql

package data

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (
    feed_id,
    title,
    author,
    content,
    external_url,
    published_at,
    created_at
)
VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateEntryParams struct {
	FeedID      int64
	Title       string
	Author      sql.NullString
	Content     string
	ExternalUrl string
	PublishedAt string
	CreatedAt   string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, createEntry,
		arg.FeedID,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.ExternalUrl,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	return err
}
