// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

import (
	"database/sql"
)

type Entry struct {
	ID          int64
	FeedID      int64
	Title       string
	Author      sql.NullString
	Content     string
	ExternalUrl string
	PublishedAt string
	Read        int64
	Starred     int64
	CreatedAt   string
}

type Feed struct {
	ID        int64
	Title     string
	FeedUrl   string
	SiteUrl   string
	Type      string
	Disabled  int64
	CheckedAt string
	UpdatedAt string
}
